server:
  port: 8080
  tomcat:
    max-http-form-post-size: 10MB

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=HorseRacingDB;encrypt=true;trustServerCertificate=true
    username: ${DB_USER:sa}
    password: ${DB_PASSWORD:12345}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServerDialect
